# BEGIN: PRE RULES
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = no
AUTO_SHIFT_ENABLE = no
TAP_DANCE_ENABLE = no
CAPS_WORD_ENABLE = no
KEY_OVERRIDE_ENABLE = yes
# END: PRE RULES

VIA_ENABLE = no
SRC += muse.c

# BEGIN: POST RULES
# END: POST RULES
