# BEGIN: PRE RULES
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
TAP_DANCE_ENABLE = yes
CAPS_WORD_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
# END: PRE RULES

VIA_ENABLE = yes
SRC += muse.c

# BEGIN: POST RULES
# END: POST RULES
