name: Build QMK firmware
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli

    steps:

    - name: Disable git safe directory checks
      run : git config --global --add safe.directory '*'

    - name: Checkout QMK
      uses: actions/checkout@v3
      with:
        repository: qmk/qmk_firmware
        submodules: recursive

    - name: Checkout userspace
      uses: actions/checkout@v3
      with:
        path: keyboards/preonic/keymaps/fwfurtado
    
    - name: Add keymap
      run: |      
       ls -l      
       ls -l keyboards/preonic/keymaps/fwfurtado

    - name: Build firmware
      run: qmk compile -c -kb preonic/rev3_drop -km fwfurtado

    - name: Archive firmware
      uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        name: ${{ github.actor }}
        path: |
          *.hex
          *.bin
          *.uf2
